### ISSUE TITLE
Building for Windows has been switched with Building for MacOS

### ISSUE THREAD

**Issue by CodeByRiley** [deslon/supernova#1]
![image](https://user-images.githubusercontent.com/53848716/203095634-fae7c494-2aa0-4674-94d0-2c578329ddce.png)
![image](https://user-images.githubusercontent.com/53848716/203095680-fae8af75-bef4-4a25-b1a0-59e1afea96b0.png)

**Comment by eduardodoria** [comment]
Fixed: https://github.com/supernovaengine/supernova-docs/commit/e1563ceab40eefed16d87986aa25b16787c509b7
Thanks.
