### ISSUE TITLE
error: It appears you haven't enabled any of the back-ends. Please #define one or more of the WITH_ defines (or use premake) '

### ISSUE THREAD

**Issue by Martinfx** [deslon/supernova#11]
hi,
i tried build your engine but i have problem with #defines

this is my edited Makefile for FreeBSD
[CMakeLists.txt](https://github.com/user-attachments/files/17448129/CMakeLists.txt)

```
cmake \
-S . \
-B build \
-DCMAKE_BUILD_TYPE=Debug \
-G "Unix Makefiles" \
-DCMAKE_INSTALL_PREFIX:PATH=instdir

```

uname -a
FreeBSD hades 13.3-RELEASE-p6 FreeBSD 13.3-RELEASE-p6 GENERIC amd64

FreeBSD clang version 17.0.6 (https://github.com/llvm/llvm-project.git llvmorg-17.0.6-0-g6009708b4367)
Target: x86_64-unknown-freebsd13.3

**Comment by eduardodoria** [comment]
I added these changes in https://github.com/supernovaengine/supernova/commit/139a0f2c0cf947c16378a7bb4a02c5b71b9ec9b6
Thanks!
