### ISSUE TITLE
Request for Instancing Support in Text Rendering

### ISSUE THREAD

**Issue by iomeone** [deslon/supernova#13]
My app needs to render thousands of characters in 3D space, and instancing would be a more efficient approach. 
Since each character uses the same quad with different positions and UVs, instancing could reduce draw calls and improve performance. Could you provide some guidance on how to use instancing to render text in 3D space  or provide a small code example to demonstrate how to use instancing to render text in 3D space? Thank you!

**Comment by eduardodoria** [comment]
Instancing is now supported only for meshes, not for text (or any 2D entities). I will analyze how I can change it to support 2D instances and get back soon.

**Comment by iomeone** [comment]
Thanks again for your efforts， look forward to any updates or ideas you might have on this.

**Comment by eduardodoria** [comment]
I wall thinking about this and I don't know if is possible to have text instancing. Each text has a different geometry. Each letter is a rect with 4 vertices. To have instancing you must have the same geometry.

I think the way we can do this is modifying the TextComponent to draw many texts in many positions with only one draw call.

Unless you need to use the same text multiple times. But if you want this you can do it with a Sprite, instead of a standard texture you can use a texture of text. The sprite is a Mesh too, so it is possible to create instances.

This is a very simple sample:

```
Sprite sprite = new Sprite(scene);
sprite->setTexture(<text in png format here>)

sprite->addInstance(Vector3(10, 10, 10)); // position of first instance
sprite->addInstance(Vector3(20, 20, 20)); // position of second instance
```

**Comment by iomeone** [comment]
I drew a simple triangle:

```
triangle.addVertex(0, -100);
triangle.addVertex(-50, 50);
triangle.addVertex(50, 50);

triangle.setPosition(Vector3(300, 300, 0));
triangle.setColor(0.6, 0.2, 0.6, 1);
```


I see that the third parameter of the addAttribute function controls whether instancing is used.

```
       void addAttribute(AttributeType attribute, int elements, bool perInstance);

	ui.buffer.addAttribute(AttributeType::POSITION, 3， true);
	ui.buffer.addAttribute(AttributeType::TEXCOORD1, 2， true);
        ui.buffer.addAttribute(AttributeType::COLOR, 4， true);
```
    
If I set the third parameter to true, the triangle doesn’t display.

**Comment by eduardodoria** [comment]
This `perInstance` says the render that this attribute is used for instancing, but the shader must support this, you cannot set it true for any attribute without modifying the shader.

To make instances of this triangle you need first change type of triangle to `MeshPolygon` instead of `Polygon` and do like this:

```
triangle.addInstance(Vector3(10, 10, 10)); // position of first instance
triangle.addInstance(Vector3(20, 20, 20)); // position of second instance
```

**Comment by iomeone** [comment]
> I wall thinking about this and I don't know if is possible to have text instancing. Each text has a different geometry. Each letter is a rect with 4 vertices. To have instancing you must have the same geometry.
> 
> I think the way we can do this is modifying the TextComponent to draw many texts in many positions with only one draw call.
> 
> Unless you need to use the same text multiple times. But if you want this you can do it with a Sprite, instead of a standard texture you can use a texture of text. The sprite is a Mesh too, so it is possible to create instances.
> 
> This is a very simple sample:
> 
> ```
> Sprite sprite = new Sprite(scene);
> sprite->setTexture(<text in png format here>)
> 
> sprite->addInstance(Vector3(10, 10, 10)); // position of first instance
> sprite->addInstance(Vector3(20, 20, 20)); // position of second instance
> ```



I wrote an example:

https://github.com/iomeone/jucesokoltest/blob/step9_SDF_CHAR/Source/render.cpp

The code is here. This example also uses the Sokol stb_text library. The relevant part of the code is:

```

// Loop to generate character instances
for (int y = 20; y >= -20; y -= 2) {
    for (int x = -20; x <= 20; x += 2) {
        int codepoint =  text_content[char_index]; // Get the ASCII code of the current character
        int index = codepoint - first_char;       // Calculate the character's index in the array
        SDFChar& sdf_char = state.sdf_chars[index];

        // Set the UV coordinates and size for the character
        EcsText text = {
            2, 2,                      // Width and height
            sdf_char.x0, sdf_char.y0,  // UV start coordinates
            sdf_char.x1 - sdf_char.x0, // UV width
            sdf_char.y1 - sdf_char.y0  // UV height
        };

        // Set the position for the character
        EcsPosition3 pos = { static_cast<float>(x), static_cast<float>(y), 0.f };

        // Initialize the transformation matrix
        EcsTransform3 transform;
        init_transform(transform, pos);

        // Create an entity and assign components
        world.entity()
            .set<EcsPosition3>(pos)
            .set<EcsText>(text)
            .set<EcsRgb>(color)
            .set<EcsTransform3>(transform);

        // Update the character index, looping back to the start
        char_index = (char_index + 1) % text_length;
    }
}

```



This generates a quad for each character, and then:
```

text_query = world.query_builder<>()
    .with<EcsPosition3>()
    .with<EcsText>()
    .with<EcsRgb>()
    .with<EcsTransform3>().inout(flecs::InOutDefault)
    .cached()
    .build();

```
```

void SokolAttachText(flecs::entity e, SokolBufferText& b) {

    attachGeometry<SokolBufferText, EcsText>(b, text_query, [](const EcsText* text, mat4& transform, SokolBufferText& b, int32_t cursor) {
        vec3 scale = { text->width, text->height, 1.0f };
        glm_scale(transform, scale);
        b.uv_texts[cursor][0] = text->uv_x;        // u0
        b.uv_texts[cursor][1] = text->uv_y;        // v0
        b.uv_texts[cursor][2] = text->uv_w;        // u1
        b.uv_texts[cursor][3] = text->uv_h;        // v1
    });

    return;
}

```

When text component is detected, the corresponding character's UV coordinates and dimensions are stored into the instance buffer.

```


if (1) {
    sg_pass pass = {
        .action = {
            .colors = { {.load_action = SG_LOADACTION_LOAD } }
        },
        .swapchain = {.width = global_width, .height = global_height }
    };

    sg_begin_pass(pass);

    sg_apply_pipeline(canvas.pipe_text);

    world.each([&](flecs::entity e, SokolBufferText& buffer) {
        if (buffer.instance_count == 0) {
            return;
        }

        sg_bindings bind = {
            .vertex_buffers = {
                buffer.vertex_buffer,
                buffer.normal_buffer,
                buffer.color_buffer,
                buffer.material_buffer,
                buffer.uv_text_buffer,
                buffer.transform_buffer,
            },
            .index_buffer = buffer.index_buffer,

            .fs = {
                .images = { state->sdfimage },
                .samplers = { canvas.smp }
            }
        };

        sg_apply_bindings(&bind);

        sg_apply_uniforms(SG_SHADERSTAGE_VS, 0, { .ptr = &vs_u, .size = sizeof(vs_uniforms_t) });
        sg_apply_uniforms(SG_SHADERSTAGE_VS, 1, { .ptr = &mat_u, .size = sizeof(vs_materials_t) });
        sg_apply_uniforms(SG_SHADERSTAGE_FS, 0, { .ptr = &fs_u, .size = sizeof(fs_u) });

        sg_draw(0, buffer.index_count, buffer.instance_count);
    });

    sg_end_pass();
}

```


Here, text instancing is implemented, and we can perform instanced rendering of text! However, this code is very primitive and cannot be directly applied to my app. Therefore, I hope your engine can add support for text instancing. Thank you!

**Comment by eduardodoria** [comment]
There is no easy way to implement this in Supernova, because I treat text as a single geometry for all characters. This approach is better if you are using less texts in scene because you call one draw per text. In your implementation, if I am understanding, you are using one geometry per character, so if I have 255 chars I need to make 255 draw calls.

I don't know if this approach is interesting for a game engine. But you can keep it open if you want. I'm very busy now but I was planned to try someting when possible.
