### ISSUE TITLE
Linux build not working

### ISSUE THREAD

**Issue by Rodieey** [deslon/supernova#2]
i used both cmake and python option and i get the same log

supernova-project: /build/glfw/src/glfw-3.3.8/src/input.c:886: glfwSetMouseButtonCallback: Assertion `window != NULL' failed.
[1]    11413 IOT instruction (core dumped)  ./supernova-project

idk if this my machine not working but it seems to not work

**Comment by eduardodoria** [comment]
Do you have `libglfw3-dev` package installed?

If you are in Ubuntu is the command:
`sudo apt install libglfw3-dev`

**Comment by Rodieey** [comment]
i had the GLFW package installed so i looked at the other GLFW packages and i found glfw-x11 package which makes the engine running and its the right package in arch based linux if im correct 
if anyone gets this eror in arch linux try to install this package like this 
sudo pacman -S glfw-x11

**Comment by eduardodoria** [comment]
Great!
Documentation is still very incomplete. I will try to document more build details as soon as possible.
