### ISSUE TITLE
GLTF Skeletal Mesh animation goes crazy at runtime (from the samples)

### ISSUE THREAD

**Issue by alfredbaudisch** [deslon/supernova#3]
I was playing around with the engine and I built the [skeletal animation sample](https://github.com/supernovaengine/supernova-samples/tree/master/skeletal_animation), without any changes, and this is the result:

https://user-images.githubusercontent.com/248383/230620710-d5cbadbf-2c7a-4c62-95e8-74760fd2b779.mp4

Any way that I can help debugging this? How can I see runtime logs? Even when building with "Debug", I can't seem to get debug output.

## Versions
- Windows 10 64-bit
- Supernova from master branch
- VS2022

**Comment by eduardodoria** [comment]
Yes, I can reproduce it. I am trying to find the problem and will back with solution as soon as possible.

**Comment by eduardodoria** [comment]
It is a DirectX problem. You can temporary use with OpenGL in Windows by uncomenting GRAPHIC_BACKEND in CMakeLists.txt:

```
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
        #set(GRAPHIC_BACKEND "d3d11")
        set(GRAPHIC_BACKEND "glcore33")
```

I am thinking a workaround for this in next days.

**Comment by eduardodoria** [comment]
Fixed in master branch.

![Captura de tela 2023-04-10 233338](https://user-images.githubusercontent.com/11426911/231040692-7095765a-977c-4297-8eb7-c5b7fc414bec.png)
