### ISSUE TITLE
issue with opening in windows

### ISSUE THREAD

**Issue by Mech3mist** [deslon/supernova#9]
Hello! I found your engine and was really interested in it! I was installing it based on your supernova documents. I went step by stet starting under "Building for Windows".  Once done I went back to "Creating a basic project" and updated the main.cpp in the project/ folder.

After that I started the project by running the .exe in instdir/bin. When I did that I got a window to open with the supernova logo. However nothing happened after that. It just sat there.

Fortunately I did see in the "Creating a basic project" documents at the very bottom that I need to build and install again. However when I did, and ran the executable again I got the same window, but just a purple triangle showed up this time. The program didn't do anything beyond that. 

Is there something I can do to fix this issue and open the engine?

**Comment by eduardodoria** [comment]
The behavior displayed was exactly what should happen. It is not an issue.

The default project is only a centered image with Supernova logo.
The "Creating a basic project" is just a simple triangle.

You can see more complex examples in https://samples.supernovaengine.org/.

I know documentation is very weak now, but my focus now is to finsh Supernova editor first release.
